name: Install and Test
on: [push]

jobs:

  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: sudo chmod +x install.sh && ./install.sh

    - name: Build
      run: rpi_blower_tester build

    - name: Test
      run: rpi_blower_tester test

    - name: Uninstall
      run: ./uninstall.sh